language: cpp
addons:
  apt:
    update: true
  artifacts:
    s3_region: "us-east-1"
    working_dir: bin

before_install:
  - pip install --user cpp-coveralls
install: make get-deps

script: make

after_success:
  - make docs
  - coveralls --exclude include/igloo --gcov-options '\-lp'
sudo: required
env:
  global:
    - EXTRACFLAGS=-Wno-deprecated-declarations

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: doxygen/html
  verbose: true
  on:
    branch: master
