language: cpp
addons:
  apt:
    update: true
install:
  - |
    sudo apt-get -y install graphviz texlive-latex-base ghostscript texlive-generic-recommended texlive-latex-extra
    sudo apt-get -y install cmake
    git clone https://github.com/doxygen/doxygen.git doxrepo
    mkdir -p doxrepo/build
    cd doxrepo/build
    export CC=/usr/bin/gcc
    cmake -G "Unix Makefiles" ..
    make
    sudo make install
    cd ../..
    rm -rf doxrepo
script:
  - make docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: doxygen/html
  verbose: true
  on:
    branch: master
sudo: required
