language: cpp
install: make get-deps
script:
  - make docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: doxygen/html
  verbose: true
  on:
    branch: master
sudo: required
