language: cpp
addons:
  apt:
    update: true
before_install:
  - pip install --user cpp-coveralls
install: make get-deps
after_success:
  - make docs; cat docs/_formulas.log
  - coveralls --exclude include/igloo --gcov-options '\-lp'
sudo: required
env:
  global:
    - EXTRACFLAGS=-Wno-deprecated-declarations

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: docs
  verbose: true
  on:
    branch: master
