language: cpp
addons:
  apt:
    update: true
before_install:
  - pip install --user cpp-coveralls
install: make get-deps && ./configure
script: make && make test && valgrind --error-exitcode=1 bin/test
after_success:
  - make docs
  - coveralls --exclude include/igloo --gcov-options '\-lp'
sudo: required
env:
  global:
    - EXTRACFLAGS=-Wno-deprecated-declarations

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: doxygen/html
  verbose: true
  on:
    branch: master
