version: 1.0.{build}
build_script:
- pwsh: |
    copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
    $env:PATH = $env:PATH + ";c:\MinGW\bin"
    Invoke-RestMethod -Uri https://s3.amazonaws.com/dsteinmo-libs/include-deps.zip -OutFile include-deps.zip
    Invoke-RestMethod -Uri https://s3.amazonaws.com/dsteinmo-libs/deps-win-mingw64.zip -OutFile deps-win-mingw64.zip
    Expand-Archive -Path include-deps.zip -DestinationPath .\include\ -Confirm
    Expand-Archive -Path deps-win-mingw64.zip -DestinationPath .\lib\ -Confirm
    make
    if($LASTEXITCODE -ne 0) { exit 1 }
