version: 1.0.{build}
environment:
  EXTRACFLAGS: -Wno-deprecated-declarations -Wno-placement-new
build_script:
- pwsh: |
    Invoke-RestMethod -Uri https://s3.amazonaws.com/dsteinmo-libs/include-deps.zip -OutFile include-deps.zip
    Invoke-RestMethod -Uri https://s3.amazonaws.com/dsteinmo-libs/deps-win-mingw64.zip -OutFile deps-win-mingw64.zip
    Invoke-RestMethod -Uri http://tehsausage.com/mingw-to-string-gcc47.zip -Outfile cpp11patch.zip 
    Expand-Archive -Path include-deps.zip -DestinationPath .\include\
    Expand-Archive -Path deps-win-mingw64.zip -DestinationPath .\lib\
    Expand-Archive -Path cpp11patch.zip -Destinationpath .
    cp wchar.h C:\MinGW\include\.
    cp stdio.h C:\MinGW\include\.
    cp os_defines.h C:\MinGW\lib\gcc\mingw32\5.3.0\include\c++\mingw32\bits
    & C:\MinGW\msys\1.0\bin\bash -e -l -c "set && ls /mingw/lib/gcc/mingw32/5.3.0/ && cd /c/projects/blitzdg-vdg02 && make"
    if($LASTEXITCODE -ne 0) { exit 1 }
test_script:
  - dir bin&&c:\MinGW\msys\1.0\bin\bash -e -l -c "/c/projects/blitzdg-vdg02/bin/test.exe;  exit 0"
artifacts:
  - path: bin

