# mingw-w64 with gcc 7.3.0 should be in --> C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0

version: 1.0.{build}
environment:
  EXTRACFLAGS: -Wno-deprecated-declarations -Wno-placement-new
build_script:
- pwsh: |
    Invoke-RestMethod -Uri https://s3.amazonaws.com/dsteinmo-libs/include-deps.zip -OutFile include-deps.zip
    Invoke-RestMethod -Uri https://s3.amazonaws.com/dsteinmo-libs/deps-win-mingw64.zip -OutFile deps-win-mingw64.zip
    Expand-Archive -Path include-deps.zip -DestinationPath .\include\
    Expand-Archive -Path deps-win-mingw64.zip -DestinationPath .\lib\
    & C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\msys\1.0\bin\bash -e -l -c "set && ls /mingw-w64/x86_64-6.3.0-posix-seh-rt_v5-rev1/lib/gcc/mingw32/5.3.0/ && cd /c/projects/blitzdg-vdg02 && make"
    if($LASTEXITCODE -ne 0) { exit 1 }
test_script:
  - dir bin&&C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\msys\1.0\bin\bash -e -l -c "/c/projects/blitzdg-vdg02/bin/test.exe;  exit 0"
artifacts:
  - path: bin

