version: 2
jobs:
  checkout:
    docker:
      - image: circleci/python:stretch
    steps:
      - checkout
      - run:
          name: Pull git submodules
          command: | 
            git submodule update --init --recursive
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  build:
    docker:
      - image: dsteinmoeller/blitzdgmanylinux:0.4.0
    steps:
      - attach_workspace:
          at: /root/project
      - run:
          name: Build (gcc)
          command: |
            CXX='g++' cmake .
            CXX='g++' make -j4
            /opt/_internal/cpython-3.8.7/bin/python3.8 setup.py bdist_wheel sdist
            cp /root/project/pyblitzdg/libblitzdg.so /usr/lib64/libblitzdg.so
            for whl in dist/*.whl; do
              auditwheel repair "$whl" --plat manylinux2010_x86_64 -w wheelhouse/
            done

      - run:
          name: Test
          command: mv bin/tests bin/test && LD_LIBRARY_PATH=/usr/local/lib bin/test

workflows:
  version: 2
  checkout_and_build:
    jobs:
      - checkout
      - build:
          requires:
            - checkout