version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: dsteinmoeller/blitzdg-circle:0.10
    environment:
      EXTRACFLAGS: "-Wno-deprecated-declarations"

    steps:
      - checkout
      - run:
          name: Pull git submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Build (clang)
          command: CXX=clang++ make -j4 && make clean
      - run:
          name: Build (gcc)
          command: CXX='g++ -Og' make -j4
      - run:
          name: Test
          command: make test
      - run:
          name: Valgrind
          command: make -j4 valgrind && make valgrind-print
      - run:
          name: Code Coverage
          command: coveralls --exclude include/igloo --gcov-options '\-lp'
