version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: dsteinmoeller/blitzdg-circle:0.11
    environment:
      EXTRACFLAGS: "-Wno-deprecated-declarations"

    steps:
      - checkout
      - run:
          name: Pull git submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Build (clang)
          command: CXX=clang++ make -j4 && make clean
      - run:
          name: Build (mingw)
          command: |
            cp /usr/include/metis.h include/.
            ln -s /usr/include/suitesparse include/suitesparse
            ln -s /usr/include/boost include/boost
            CXX=x86_64-w64-mingw32-g++-posix make -j4 && make clean
      - run:
          name: Build (gcc)
          command: CXX='g++ -Og' make -j4
      - run:
          name: Test
          command: make test
      - run:
          name: Valgrind
          command: make -j4 valgrind && make valgrind-print
      - run:
          name: Code Coverage
          command: coveralls --exclude include/igloo --gcov-options '\-lp'
