version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: dsteinmoeller/blitzdg-circle:0.13

    steps:
      - checkout
      - run:
          name: Pull git submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Build (clang)
          command: CXX=clang++ INC="-I /opt/blitzpp/blitz-1.0.1" make -j4 && make clean
      - run:
          name: Build (mingw)
          command: |
            apt-get -y install gfortran-mingw-w64-x86-64
            curl https://s3.amazonaws.com/dsteinmo-libs/include-deps.zip -o include-deps.zip
            mkdir -p mingw-include
            unzip -qq include-deps.zip -d mingw-include/
            rm -rf mingw-include/igloo
            curl https://s3.amazonaws.com/dsteinmo-libs/deps-win-mingw64-gcc7.zip -o deps-win-mingw64.zip
            unzip -qq deps-win-mingw64.zip -d lib/
            CXX=x86_64-w64-mingw32-g++-posix INC="$INC -I mingw-include/" LIB="-L lib" make -j4 && make clean
      - run:
          name: Build (gcc)
          command: CXX='g++ -Og' INC="-I /opt/blitzpp/blitz-1.0.1" make -j4
      - run:
          name: Test
          command: make test
      - run:
          name: Valgrind
          command: make -j4 valgrind && make valgrind-print
      - run:
          name: Code Coverage
          command: coveralls --exclude include/igloo --gcov-options '\-lp'
