version: 2
jobs:
  checkout:
    docker:
      - image: dsteinmoeller/blitzdg-circle:0.16
    steps:
      - checkout
      - run:
          name: Pull git submodules
          command: | 
            git submodule update --init --recursive
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  build:
    docker:
      - image: dsteinmoeller/blitzdgmanylinux:0.3.1
    steps:
      - attach_workspace:
          at: /root/project
      - run:
          name: Generate makefiles
          command: |
            DEBUG=1 CXX=clang++ INC="-I /opt/blitzpp/blitz-1.0.1" cmake .
      - run:
          name: Build (clang)
          command: |
            DEBUG=1 CXX=clang++ INC="-I /opt/blitzpp/blitz-1.0.1" make -j4
            make clean
            rm -rf CMakeFiles/ CMakeCache.txt
      - run:
          name: Build (gcc)
          command: |
            DEBUG=1 CXX='g++ -Og' INC="-I /opt/blitzpp/blitz-1.0.1" cmake .
            DEBUG=1 CXX='g++ -Og' INC="-I /opt/blitzpp/blitz-1.0.1" make -j4
      - run:
          name: Test
          command: mv bin/tests bin/test && LD_LIBRARY_PATH=/usr/local/lib bin/test

workflows:
  version: 2
  checkout_and_build:
    jobs:
      - checkout
      - build:
          requires:
            - checkout