version: 2
jobs:
  build:
    docker:
      - image: dsteinmoeller/blitzdg-circle:0.10
    steps:
      - checkout
      - run:
          name: Build
          command: make
      - run:
          name: Test
          command: make test
      - run:
          name: Valgrind
          command: for filename in bin/* ; do \
                     valgrind --error-exitcode=1 --leak-check=full --track-origins=yes "$filename"; \
                   done